apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          memory: "120Mi"
          CPU: "500m"
        ports:
        - containerPort: 80