apiVersion: apps/v1
kind: Deployment
metadata:
  name: marj-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: kiamol/ch02-whoami
          ports:
            - containerPort: 8080

