apiVersion: apps/v1
kind: Deployment
metadata:
  name: ainur.deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ainur
  template:
    metadata:
      labels:
        app: ainur
    spec:
      containers:
        - name: ainur
          image: kiamol/ch02-whoami
          ports:
            - containerPort: 8080