apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seytech
  name: myapp
  labels:
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - containerPort: 80


