apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: seytech
  name: nginix-pv-volume
  labels:
    name: nginix-pv-volume
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


